import "@assets/styles/main.css";
import { Navbar } from "@cs-magic/react/components/navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Banner = () => {
  return "Home";
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar productBanner={<Banner />} />

        <div className="bg-gradient-to-br from-purple-600 to-blue-500 flex items-center justify-center p-4 h-screen overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
