import "@assets/styles/main.css"

import { Navbar } from "@cs-magic/react/components/navbar"

import { ReactQueryProvider } from "@/components/react-query.provider.tsx"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Banner = () => {
  return "Home"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`antialiased`} suppressHydrationWarning>
          <Navbar productBanner={<Banner />} />

          <div className="bg-gradient-to-br from-purple-600 to-blue-500 flex items-center justify-center p-4 h-screen overflow-hidden">
            {children}
          </div>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
