import { Navbar } from "@cs-magic/react/components/navbar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@cs-magic/shadcn/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
} from "@cs-magic/shadcn/ui/select";
import type { Metadata } from "next";
import { Poor_Story } from "next/dist/compiled/@next/font/dist/google";
import localFont from "next/font/local";
import "@assets/styles/main.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Banner = () => {
  return "Home";
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar productBanner={<Banner />} />
        {children}
      </body>
    </html>
  );
}
